### ISSUE TITLE
Get CRuby `make test-all` passing

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2254]
- [x] https://github.com/ruby/prism/issues/1997
  - Will probably fix `test/ruby/test_m17n.rb` and `test/ruby/test_regexp.rb`
- [ ] #2370
- [ ] #2323
- [ ] `TestRubyLiteral#test_string` https://github.com/ruby/prism/issues/2331
- [x] #2369
- [x] #2371
- [x] `TestParse#test_method_location_in_rescue` - line number is off
- [x] `TestSetTraceFunc#test_thread_add_trace_func` - line number is off
- [x] `TestSyntax#test_method_call_location` - line number is off
- [x] `TestString#test_concat_literals` - concat is losing encoding (https://github.com/ruby/prism/issues/2313)
- [x] #2309
- [x] `TestFileExhaustive#test_expand_path_encoding` - encoding issue
- [x] <https://github.com/ruby/ruby/pull/9821>: `TestCall#test_call_block_order` splat with block swallowed
- [x] `test/ruby/test_shapes.rb`: pending https://github.com/ruby/ruby/pull/9812
- [x] #2326
- [x] `Psych_Unit_Tests#test_spec_explicit_families` - almost definitely encoding related
- [x] `test/test_unicode_normalize.rb` - probably encoding related
- [x] `test/objspace/test_objspace.rb` - code range/old??
- [x] `TestZlibGzipReader#test_gets2` - encoding related
- [x] #2321
- [x] #2312
- [x] #2316
- [x] #2311
- [x] #2318
- [x] #2307
  - `test/optparse/test_acceptable.rb`
  - `test/optparse/test_cclass.rb`
  - `test/optparse/test_did_you_mean.rb`
  - `test/optparse/test_optparse.rb`
  - `test/optparse/test_optarg.rb`
  - `test/optparse/test_noarg.rb`
  - `test/optparse/test_reqarg.rb`
  - `test/optparse/test_placearg.rb`
  - `test/optparse/test_summary.rb`
- [x] `TestMethod#test_method_list` - segfaults - https://github.com/ruby/prism/issues/2294
- [x] #2314
- [x] #2310
- [x] https://github.com/ruby/prism/issues/1998
- [x] https://github.com/ruby/prism/issues/2245
- [x] https://github.com/ruby/prism/issues/2247
- [x] https://github.com/ruby/prism/issues/2248
- [x] https://github.com/ruby/prism/issues/2249
- [x] https://github.com/ruby/prism/issues/2250
- [x] https://github.com/ruby/prism/issues/2251
- [x] https://github.com/ruby/prism/issues/2252
- [x] https://github.com/ruby/prism/issues/2253
- [x] `TestProfileFrames#test_matches_backtrace_locations_main_thread` - segfaults, unknown reason (https://github.com/ruby/prism/issues/2295)
- [x] `unknown type: T_STRING`
  - `test/did_you_mean/core_ext/test_name_error_extension.rb`
  - `test/did_you_mean/spell_checking/test_method_name_check.rb`
  - `test/did_you_mean/spell_checking/test_variable_name_check.rb`
  - `test/error_highlight/test_error_highlight.rb`
  - `test/irb/test_eval_history.rb`
- [x] #2296
- [x] `test/monitor/test_monitor.rb` - `# ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: x)` (https://github.com/ruby/prism/issues/2299)
- [x] Anonymous local variables incorrectly named, will be fixed by #2276
- [x] #2298
- [x] #2300
- [x] #2297
- [x] #2324
- [x] `TestSyntax#test_must_ascii_compatible` - https://bugs.ruby-lang.org/issues/20210

**Comment by kddnewton** [comment]
Closing in favor of https://github.com/ruby/prism/issues/2791
