### ISSUE TITLE
CRuby tests/specs passing

### ISSUE THREAD

**Issue by kddnewton** [ruby/prism#2791]
## Pending response

- [ ] `TestM17N#test_regexp_usascii` - (https://bugs.ruby-lang.org/issues/20504)
- [ ] `TestRubyLiteral#test_dregexp` - (https://bugs.ruby-lang.org/issues/20504)
- [ ] `TestMixedUnicodeEscape#test_basic` - (https://bugs.ruby-lang.org/issues/20504)
- [ ] `TestSyntax#test_keyword_self_reference` - (https://bugs.ruby-lang.org/issues/20478)
- [ ] `TestSyntax#test_optional_self_reference` - (https://bugs.ruby-lang.org/issues/20478)

**Comment by kddnewton** [comment]
Closing now since the final two issues are dependent on response from other CRuby contributors.
